# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(844, 67)
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 821, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PB_Kalkulator = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PB_Kalkulator.setObjectName("PB_Kalkulator")
        self.horizontalLayout.addWidget(self.PB_Kalkulator)
        self.PB_EngineeringTool = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PB_EngineeringTool.setObjectName("PB_EngineeringTool")
        self.horizontalLayout.addWidget(self.PB_EngineeringTool)
        self.PB_NetworkTool = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PB_NetworkTool.setObjectName("PB_NetworkTool")
        self.horizontalLayout.addWidget(self.PB_NetworkTool)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 821, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PB_AboutUs = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.PB_AboutUs.setObjectName("PB_AboutUs")
        self.horizontalLayout_2.addWidget(self.PB_AboutUs)
        Main.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Main"))
        self.PB_Kalkulator.setText(_translate("Main", "Kalkulator"))
        self.PB_EngineeringTool.setText(_translate("Main", "Engineering Tool"))
        self.PB_NetworkTool.setText(_translate("Main", "Network Tool"))
        self.PB_AboutUs.setText(_translate("Main", "About Us"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
